# Generated by Django 2.2 on 2019-07-06 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20190706_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='Expiry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MFD',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
