# Generated by Django 2.2 on 2019-07-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_auto_20190706_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='Expiry',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MFD',
            field=models.CharField(max_length=20),
        ),
    ]
